services:
  postgres:
    image: postgres:16-alpine
    container_name: jtk-postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: jtk
      POSTGRES_PASSWORD: jtk
      POSTGRES_DB: jtk
    volumes:
      - jtk_pg_data:/var/lib/postgresql/data

volumes:
  jtk_pg_data:
